### PR TITLE
Fix issue by changing how rules are saved

### LINKED ISSUE #141: Resource Costs not added Custom Rate - Date Ranges
#### What I expected

Expected Resource costs to be added to Dates with Custom Date Range Prices

#### What happened instead

Resource costs are added to dates with no Custom Date Rage Price but are seemingly ignored on dates with prices adjustments

#### Steps to reproduce the issue

Create > Accommodation Booking Product
Enable > Resources && People
Set > Standard room rate
Set > Person Types
Set > Custom Date Range Rate (range of nights…)
Set > Custom Rate Cost
Create > Resources (x3)
Assign Resources to Product
Set > Resource block costs -> with or without base cost 

Screen shots of associated WC Product Data Tabs.

custom rate - date range
general
persons
resources

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

### PR DESCRIPTION
**Pull request by bor0**
Fixes #141.

#### Changes proposed in this Pull Request:
- See explanation at https://github.com/woocommerce/woocommerce-accommodation-bookings/issues/141#issuecomment-370357027

-------------------
- [ ] Make sure your changes respect [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [ ] Did you make changes, or create a **new .js file**? If **Gruntfile.js** exists in the repo, make sure to run `grunt`.

### CODE REVIEW

**Comment by bor0** [comment]
@laurendavissmith this is ready for reviewal. Please have a look when you can.

**Comment by bor0** [comment]
@jessepearson can you please give this one a try? Thank you.

**Comment by bor0** [comment]
Updated issue that @jessepearson caught during testing in 78277be.

**Comment by jessepearson** [comment]
Tested according to steps in bug report, and things calculate properly now 👍

**Comment by foadyousefi** [comment]
Sorry about bugging but I still have the same issue. It seems last update of the plugin on Wordpress plugins repo was 7 months ago. Will someone update it or we need to use this github repo?

woocommerce_accommodation_bookings___wordpress_org

**Comment by laurendavissmith** [comment]
@foadyousefi we should have a release for this extension going out in the next several weeks

**Pull request merged**
