### PR TITLE
Expose the `accommodation-booking` product type to the REST API

### LINKED ISSUE #401: REST API accomodation-booking product creation not possible
#### What I expected

Being able to create an Accomodation booking through API.

There's no ```WC_Accomodation_Bookings_REST_Products_Controller``` so we have to use ```WC_Bookings_REST_Products_Controller``` which could be fine if method ```prepare_object_for_database()``` was not enforcing ```$request['type'] = 'booking'```.

#### What happened instead

It enforces type booking so my products ends up "Bookable products" and not "Accomodation products". 

#### Steps to reproduce the issue
```php
$request = [
    'name' => 'new product name', 
    // more properties
];
$wpRequest = new WP_REST_Request('POST');
$request['type'] = 'accommodation-booking'; // to create a WC_Product_Accommodation_Booking
$wpRequest->set_body_params($request);

$controller = new WC_Bookings_REST_Products_Controller();
$result = $controller->create_item($wpRequest);
```
=> ```$result['type'] === 'booking'```

I guess it's more a woocommerce-bookings bug but it's so related to this one I tried my chance here.

If instead of using ```WC_Bookings_REST_Products_Controller```, we use ```WC_REST_Products_Controller```, the product class is the right one (but with none of the product customization done in ```WC_Bookings_REST_Products_Controller::prepare_object_for_database()``` method

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

### PR DESCRIPTION
**Pull request by faisal-alvi**
### All Submissions:

* [ ] Does your code follow the [WooCommerce Sniffs](https://github.com/woocommerce/woocommerce-sniffs/) variant of WordPress coding standards?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?
* [ ] Will this change require new documentation or changes to existing documentation?

---

### Changes proposed in this Pull Request:

The custom product type `accommodation booking` was added to the plugin at:

https://github.com/woocommerce/woocommerce-accommodation-bookings/blob/ad98ad681a8197d202327af7a1d6080952cd1b15/includes/admin/class-wc-accommodation-booking-admin-panels.php#L49

However, when a product is created or updated via the REST API, it throws this error as noted in https://github.com/woocommerce/woocommerce-accommodation-bookings/issues/435#issue-2313206689:

```
"type": "type is not one of simple, grouped, external, variable, and booking."
```

This error indicates that the custom product type `accommodation-booking` is not accessible through the REST API. The problem originates from the following code, which restricts its accessibility:

https://github.com/woocommerce/woocommerce-accommodation-bookings/blob/ad98ad681a8197d202327af7a1d6080952cd1b15/includes/class-wc-accommodation-bookings-plugin.php#L124-L127

This PR addresses the issue by exposing the custom product type `accommodation-booking` to the REST API.

Closes #401.

### Steps to test the changes in this Pull Request:

See the details at https://github.com/woocommerce/woocommerce-accommodation-bookings/issues/435#issue-2313206689 and confirm the issue is resolved.

Note: This PR requires another fix which is made at https://github.com/woocommerce/woocommerce-bookings/pull/3809. Please use them together to test the fix.

### Changelog entry

> Fix - Error in Updating Accommodation Product Data via REST API: Unrecognized Product Type Response

### CODE REVIEW

**Review by dkotter — COMMENTED** [review]
Overall this looks good to me but what this change does mean is anytime a REST request is made to the `wp-json/wc-bookings` endpoint, we are loading extra functionality that is mostly not needed. Is there any potential for this to cause problems or impact performance on those requests? Wondering if there's a simpler way to ensure this product type is available to the REST API

**Comment by faisal-alvi** [comment]
<p>@dkotter That's a good point. However, I reviewed the codebase and confirmed that while we are loading some additional functionality, it doesn't appear to be causing any issues or affecting performance. Additionally, not all of the functionality is redundant; I think we do need <code>WC_Accommodation_Booking_Admin_Panels::save_product_data</code>.</p>

<p>To avoid unnecessary exposure, we can relocate <code>WC_Accommodation_Booking_Admin_Panels::product_type_selector</code> and <code>WC_Accommodation_Booking_Admin_Panels::save_product_data</code> to a new class, making them accessible only through the REST endpoint. Please let me know if we should proceed with this change.</p>

**Comment by dkotter** [comment]
> To avoid unnecessary exposure, we can relocate WC_Accommodation_Booking_Admin_Panels::product_type_selector and WC_Accommodation_Booking_Admin_Panels::save_product_data to a new class, making them accessible only through the REST endpoint. Please let me know if we should proceed with this change.

My preference would be to only load whatever functionality is actually needed, assuming that isn't too much effort. But let me know if you don't think that's a wise approach and we can reconsider

**Comment by faisal-alvi** [comment]
I agree that we should load only the required functionality. I can see the following 2 functions are required in REST API. So instead of exposing the full class, what if we should move these 2 classes to the `class-wc-accommodation-bookings-plugin.php`, thoughts? I can see `FOUND 139 ERRORS AND 33 WARNINGS AFFECTING 88 LINES` which need to be addressed if we move them though.

https://github.com/woocommerce/woocommerce-accommodation-bookings/blob/ad98ad681a8197d202327af7a1d6080952cd1b15/includes/admin/class-wc-accommodation-booking-admin-panels.php#L136

https://github.com/woocommerce/woocommerce-accommodation-bookings/blob/ad98ad681a8197d202327af7a1d6080952cd1b15/includes/admin/class-wc-accommodation-booking-admin-panels.php#L48

**Comment by ankitguptaindia** [comment]
@dkotter @faisal-alvi Is this ready for QA issue https://github.com/woocommerce/woocommerce-accommodation-bookings/issues/401 ?

**Comment by faisal-alvi** [comment]
@ankitguptaindia no, I'm working on it.

**Review by dkotter — APPROVED** [review]

**Comment by ankitguptaindia** [comment]
**QA/Test Report-** ✅ 
------------

**Testing Environment -** 

<Details>

* WordPress: 6.5.4
* Theme: Storefront Version: 4.5.4 / Twenty Twenty-Four Version: 1.1
* WooCommerce - Version 9.1.0 Dev
* PHP: 8.3
* Web Server: Nginx
* Browser: Chrome - Version 126
* OS: macOS Sonoma 14.4.1 
* Git Branch: https://github.com/woocommerce/woocommerce-bookings/tree/fix/accom-401 & 
https://github.com/woocommerce/woocommerce-accommodation-bookings/tree/fix/401 

</Details>


**Test Results -** The Issue has been fixed. 'accommodation-booking' type product can be updated via REST API. 

**Functional Demo /  Screencast -**

https://github.com/woocommerce/woocommerce-bookings/assets/6384299/62021dbf-ec2d-4cf3-9785-448a29a28110


**Next Step-** Ready to UAT 🎉 


Please note: This PR should merge/release together with another connected PR https://github.com/woocommerce/woocommerce-bookings/pull/3809

**Review by ankitguptaindia — APPROVED** [review]

**Comment by ankitguptaindia** [comment]
**Regression+Smoke Test Report-** ✅ 
------------

**Testing Environment -** 


<Details>

* WordPress: 6.5.5
* Theme: Storefront Version: 4.6.0 / Twenty Twenty Four: Version: 1.1
* WooCommerce - Version 9.0.2 
* PHP: 8.3.0 
* Web Server: Nginx
* Browser: Chrome - Version 126
* OS: macOS Sonoma V 14.4.1  

</Details>

Tested with Archive File created via 

```php woorelease.phar build https://github.com/woocommerce/woocommerce-accommodation-bookings/tree/smoke-testing```

- Composer version - v2.3.5
- npm version - v10.8.1
- node version - v20.140

#### Please note that this plugin has been tested with the build created by the specified versions ☝🏼 of Composer, Node, and NPM. 



**Status-**  Working as expected. Ready to merge 🚀

**Pull request merged**
