### PR TITLE
Bump Woo tested upto 7.8

### LINKED ISSUE #341: Compatibility testing with WooCommerce 7.8
With WooCommerce 7.8 RC 1 out, perform the following:

- [ ] Test the extension thoroughly with WC 7.8
- [ ]  Add compatibility fixes, where necessary
- [ ]  Bump WooCommerce "Tested up to" to 7.8
- [ ]  Bump WooCommerce minimum supported to 7.2
- [ ]  Bump WordPress minimum supported to 6.1
- [ ]  Scan for any conditional checks that may be in the code that can be removed with this "Tested up to" and minimum bumps

Sample Changelog entry should then be:
> Dev - Bump WooCommerce "tested up to" version 7.8.
> Dev - Bump WooCommerce minimum supported version from X.X to 7.2.
> Dev - Bump WordPress minimum supported version from X.X to 6.1.

### PR DESCRIPTION
**Pull request by kirtangajjar**
### All Submissions:

* [x] Does your code follow the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changes proposed in this Pull Request:

Closes #341.

### How to test the changes in this Pull Request:

Smoke test with 7.8

Tested following:
* [x] Accommodation product checkout without issues.
* [x] Accommodation product with resources.
* [x] Accommodation product with persons.
* [x] Updating the order status also updates the bookings’ status.
* [x] Accommodation product without resources.

### Other information:

* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changelog entry

> Dev - Bump WooCommerce "tested up to" version 7.8.
> Dev - Bump WooCommerce minimum supported version from 6.0 to 7.2.
> Dev - Bump WordPress minimum supported version from 5.6 to 6.1.

### CODE REVIEW

**Review by faisal-alvi — APPROVED** [review]

**Comment by ankitguptaindia** [comment]
Hey @kirtangajjar Could you resolve the conflict in this PR?

**Comment by kirtangajjar** [comment]
@ankitguptaindia Conflicts resolved!

**Comment by ankitguptaindia** [comment]
The only changes are version bumps in this PR. Will Test in regression/smoke test together with other PRs. 

cc: @vikrampm1 @jeffpaul 

**Next Step-** UAT.

**Comment by dkotter** [comment]
@kirtangajjar Looks like there's also a `readme.txt` file in this repo that will need these versions bumped

**Comment by kirtangajjar** [comment]
@dkotter Updated the PR as per your request.

**Review by dkotter — APPROVED** [review]

**Comment by ankitguptaindia** [comment]
**Regression+Smoke Test Report-** ✅ 
------------

**Testing Environment -** 


<Details>

* WordPress: 6.2.2
* Theme: Storefront Version: 4.2.0
* WooCommerce - Version 7.8.2
* PHP: 8.0.22 
* Web Server: Nginx
* Browser: Chrome - Version 113


</Details>


Tested with Archive File created via 

```php woorelease.phar build smoke-testing branch _URL_ ```

- Composer version - 2.3.5
- npm version - 6.14.14
- node version - v14.17.5

#### Please note that this plugin has been tested with the build created by the specified versions of Composer, Node, and NPM.



**Status-**  Working as expected. Ready to merge 🚀

cc: @vikrampm1

**Review by ankitguptaindia — APPROVED** [review]

**Pull request merged**
