### PR TITLE
Fix fatal error in case the plugin is included multiple times.

### LINKED ISSUE #105: Fatal Error: Cannot redeclare class WC_Product_Accommodation_Booking
When I updated the WooCommerce Accommodation Bookings plugin today, it failed with the error

Fatal error: Cannot redeclare class WC_Product_Accommodation_Booking in /xxx/htdocs/xxx/wp-content/plugins/woocommerce-accommodation-bookings/includes/class-wc-product-accommodation-booking.php on line 151

I was able to "fix" this by going to woocommerce-bookings/includes/addons/accommodation-booking.php and commenting out the following code:
**
 * Simple structure for a MVP "working" accommodation product class.
 * Only to be used if the accommodtion plugin is missing so we don't fatal.
 */
	class WC_Product_Accommodation_Booking extends WC_Product_Skeleton_Booking {
		public function __construct( $product ) {
			$this->product_type = 'accommodation-booking';
			parent::__construct( $product );
		}

		public function bookings_addon_title() {
			return __( 'Accommodation booking', 'woocommerce-bookings' );
		}
	}

However, this is not a correct fix. I'm going to also figure out how to contact the plugin author of the WooCommerce Booking plugin to alert them about this error.

### PR DESCRIPTION
**Pull request by bor0**
Fixes #105.

#### Changes proposed in this Pull Request:
- Wrap the class definition in a `class_exists` check

-------------------
- [ ] Make sure your changes respect [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [ ] Did you make changes, or create a **new .js file**? If **Gruntfile.js** exists in the repo, make sure to run `grunt`.

### CODE REVIEW

**Comment by jessepearson** [comment]
This fixes the fatal, but it breaks Accomm functionality with Bookings 1.9.12, tons of notices and warnings are thrown.

**Comment by bor0** [comment]
@jessepearson which WC version?

**Comment by jessepearson** [comment]
@bor0 
WC 3.0.3
Bookings 1.9.12
Accomm branch in this PR

To be honest, the users should be updating both at the same time, and if they are, there is no issue.

**Comment by gedex** [comment]
@bor0 I experienced the same issue with @jessepearson in which it works without notices with Bookings 1.10.0 but got lots of notices when using 1.9.15.

```
[18-Apr-2017 14:11:35 UTC] PHP Warning:  Declaration of WC_Product_Booking::get_price() should be compatible with WC_Product::get_price($context = 'view') in /srv/www/wordpress-default/wp-content/plugins/woocommerce-bookings/includes/class-wc-product-booking.php on line 0
[18-Apr-2017 14:11:35 UTC] PHP Notice:  Undefined index: product-booking in /srv/www/wordpress-default/wp-content/plugins/woocommerce-accommodation-bookings/includes/class-wc-accommodation-booking.php on line 32
[18-Apr-2017 14:11:36 UTC] PHP Notice:  Undefined index: product-booking in /srv/www/wordpress-default/wp-content/plugins/woocommerce-accommodation-bookings/includes/class-wc-accommodation-booking.php on line 32
[18-Apr-2017 14:11:36 UTC] PHP Notice:  Undefined index: product-booking in /srv/www/wordpress-default/wp-content/plugins/woocommerce-accommodation-bookings/includes/class-wc-accommodation-booking.php on line 32
[18-Apr-2017 14:11:36 UTC] PHP Notice:  Undefined index: product-booking in /srv/www/wordpress-default/wp-content/plugins/woocommerce-accommodation-bookings/includes/class-wc-accommodation-booking.php on line 32
[18-Apr-2017 14:11:36 UTC] PHP Notice:  Undefined index: product-booking in /srv/www/wordpress-default/wp-content/plugins/woocommerce-accommodation-bookings/includes/class-wc-accommodation-booking.php on line 32
[18-Apr-2017 14:11:36 UTC] PHP Notice:  Undefined index: product-booking in /srv/www/wordpress-default/wp-content/plugins/woocommerce-accommodation-bookings/includes/class-wc-accommodation-booking.php on line 32
[18-Apr-2017 14:11:36 UTC] PHP Notice:  Undefined index: product-booking in /srv/www/wordpress-default/wp-content/plugins/woocommerce-accommodation-bookings/includes/class-wc-accommodation-booking.php on line 32
[18-Apr-2017 14:11:36 UTC] PHP Notice:  Undefined index: product-booking in /srv/www/wordpress-default/wp-content/plugins/woocommerce-accommodation-bookings/includes/class-wc-accommodation-booking.php on line 32
[18-Apr-2017 14:11:36 UTC] PHP Notice:  Undefined index: product-booking in /srv/www/wordpress-default/wp-content/plugins/woocommerce-accommodation-bookings/includes/class-wc-accommodation-booking.php on line 32
[18-Apr-2017 14:11:36 UTC] PHP Notice:  Undefined index: product-booking in /srv/www/wordpress-default/wp-content/plugins/woocommerce-accommodation-bookings/includes/class-wc-accommodation-booking.php on line 32
[18-Apr-2017 14:11:36 UTC] PHP Notice:  Undefined index: product-booking in /srv/www/wordpress-default/wp-content/plugins/woocommerce-accommodation-bookings/includes/class-wc-accommodation-booking.php on line 32
[18-Apr-2017 14:11:36 UTC] PHP Notice:  Undefined index: product-booking in /srv/www/wordpress-default/wp-content/plugins/woocommerce-accommodation-bookings/includes/class-wc-accommodation-booking.php on line 32
[18-Apr-2017 14:11:36 UTC] PHP Notice:  Undefined index: product-booking in /srv/www/wordpress-default/wp-content/plugins/woocommerce-accommodation-bookings/includes/class-wc-accommodation-booking.php on line 32
[18-Apr-2017 14:11:36 UTC] PHP Notice:  Undefined index: product-booking in /srv/www/wordpress-default/wp-content/plugins/woocommerce-accommodation-bookings/includes/class-wc-accommodation-booking.php on line 32
[18-Apr-2017 14:11:36 UTC] PHP Notice:  Undefined index: product-booking in /srv/www/wordpress-default/wp-content/plugins/woocommerce-accommodation-bookings/includes/class-wc-accommodation-booking.php on line 32
[18-Apr-2017 14:11:36 UTC] PHP Notice:  Undefined index: product-booking in /srv/www/wordpress-default/wp-content/plugins/woocommerce-accommodation-bookings/includes/class-wc-accommodation-booking.php on line 32
[18-Apr-2017 14:11:36 UTC] PHP Notice:  Undefined index: product-booking in /srv/www/wordpress-default/wp-content/plugins/woocommerce-accommodation-bookings/includes/class-wc-accommodation-booking.php on line 32
[18-Apr-2017 14:11:36 UTC] PHP Notice:  Action: woocommerce_product_write_panels is <strong>deprecated</strong> since version 2.6! Use Use woocommerce_product_data_panels action instead. instead. in /srv/www/wordpress-default/wp-includes/functions.php on line 3829
```

**Comment by gedex** [comment]
@bor0 I think this is caused by the fact older version of Bookings (pre 1.10.0) doesn't have the data store yet. So I believe this couldn't be fixed other than updating Bookings to 1.10.0.

**Comment by bor0** [comment]
Agree with @gedex. This has to do with Bookings version not compatible with 3.x, but it will not fatal at least so to allow them to update.

**Comment by jessepearson** [comment]
This may need to turn into a `wont fix` due to I don't think Accomm 1.0.8+ will be able to work with Bookings versions less than 1.10.0.

**Comment by bor0** [comment]
@jessepearson but I think it's better that it will not fatal, right?

**Comment by jessepearson** [comment]
@bor0 Yes, you're right. At least it won't fatal and they can still update Bookings through wp-admin

**Comment by cwuensche** [comment]
I'm currently experiencing this same issue.

**Comment by cwuensche** [comment]
I can confirm that updating WooCommerce Accommodation Bookings from 1.9.x to 1.10.x fixed these errors.

**Comment by gedex** [comment]
> I can confirm that updating WooCommerce Accommodation Bookings from 1.9.x to 1.10.x fixed these errors.

I assume updating WooCommerce Bookings from 1.9.x to 1.10.x, @cwuensche ?

**Pull request merged**
