### PR TITLE
fix/308 Handle empty Rate with Cost Rule

### LINKED ISSUE #308: Fatal Error if Standard Room Rate is not present before a rate rule is added
#### Affected ticket(s)

5518065-zd-woothemes

#### What I expected

Either to be abe able to add a **Range type** for my rates without filling in the **Standard room rate** field, or to be somehow warned if I can't do it like that. 

#### What happened instead

The Rates > Cost block shows a critical error occurred, and the Availability Tab goes blank. 

It looks a temporary fix for this bug is to make sure the **Rates tab > Standard room rate** field is not blank. Once the error has been triggered, filling the **Standard room rate** field resolves it.

#### Steps to reproduce the issue

1. Create a new product. 
2. Add a title. 
3. Switch product type to **Accommodation product**
4. Go to the **Rates tab**
5. Add: Range type > Range of certain nights | Starting 2 Oct 2022 | Ending 16 Oct 2022 | Cost : 100 > Click publish
6. Revisit the **Rates** or **Availability** tabs, notice the errors

After steps above, Rates tab: 

Availability tab: 

Error logs record: 

```
2022-08-30T12:27:41+00:00 CRITICAL Uncaught TypeError: abs(): Argument #1 ($num) must be of type int|float, string given in /Users/woohoo/Sites/woo/wp-content/plugins/woocommerce-accommodation-bookings/includes/admin/views/html-accommodation-booking-rates-fields.php:112
Stack trace:
#0 /Users/woohoo/Sites/woo/wp-content/plugins/woocommerce-accommodation-bookings/includes/admin/views/html-accommodation-booking-rates-fields.php(112): abs('')
#1 /Users/woohoo/Sites/woo/wp-content/plugins/woocommerce-accommodation-bookings/includes/admin/views/html-accommodation-booking-rates.php(46): include('/Users/woohoo/Sit...')
#2 /Users/woohoo/Sites/woo/wp-content/plugins/woocommerce-accommodation-bookings/includes/admin/class-wc-accommodation-booking-admin-panels.php(93): include('/Users/woohoo/Sit...')
#3 /Users/woohoo/Sites/woo/wp-includes/class-wp-hook.php(307): WC_Accommodation_Booking_Admin_Panels->panels('')
#4 /Users/woohoo/Sites/woo/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#5 /Users/woohoo/Sites/woo/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#6 /Users/woohoo/Sites/woo/wp-content/plugins/woocommerce/includes/admin/meta-boxes/views/html-product-data-panel.php(53): do_action('woocommerce_pro...')
#7 /Users/woohoo/Sites/woo/wp-content/plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-product-data.php(33): include('/Users/woohoo/Sit...')
#8 /Users/woohoo/Sites/woo/wp-admin/includes/template.php(1401): WC_Meta_Box_Product_Data::output(Object(WP_Post), Array)
#9 /Users/woohoo/Sites/woo/wp-admin/edit-form-advanced.php(688): do_meta_boxes(Object(WP_Screen), 'normal', Object(WP_Post))
#10 /Users/woohoo/Sites/woo/wp-admin/post.php(206): require('/Users/woohoo/Sit...')
#11 {main}
  thrown in /Users/woohoo/Sites/woo/wp-content/plugins/woocommerce-accommodation-bookings/includes/admin/views/html-accommodation-booking-rates-fields.php on line 112

```

-------------------

- [] Issue assigned to next milestone.
- [] Issue assigned a priority (will be assessed by maintainers).

### PR DESCRIPTION
**Pull request by faisal-alvi**
### All Submissions:

* [ ] Does your code follow the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changes proposed in this Pull Request:

Reopening PR #309 because the cost in the float value is no more supported because `intval` was used in #297, we should use `floatval` to support the float values in the cost.

This PR simply adds `floatval` wrapper around the product cost (ie `_wc_booking_base_cost`) to avoid fatal error when no cost is added but the cost rule is.

Closes #308.

### How to test the changes in this Pull Request:

1. Create a new accommodation product.
2. Go to the Rates tab
3. Without adding a Rate/Cost, add a Range: Range type > Range of certain nights | Starting any date | Ending any date | Cost: 100 > Click Publish.
4. Revisit the Rates or Availability tabs, there shouldn't be any errors as mentioned in the linked issue.

### Other information:

* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changelog entry

> Fix - Fatal error when Rate is empty and Range Cost is added.

### CODE REVIEW

**Comment by faisal-alvi** [comment]
@Sidsector9 assigning to you for a Code Review + QA.

**Comment by ankitguptaindia** [comment]
@faisal-alvi I tried to reproduce this issue but it's working fine with the trunk. As I can see you already mentioned, this is fixed by https://github.com/woocommerce/woocommerce-accommodation-bookings/pull/297 so is this PR an improvement for 297?

**Comment by faisal-alvi** [comment]
Yes @ankitguptaindia the original issue is fixed but if you try to add a `float` amount (for example 10.5, 11.9) you'll notice it does not save in float and converts back to the `int` value (i.e. 10, 11). This PR fixes that issue.

**Comment by ankitguptaindia** [comment]
**QA/Test Report-** ✅ 
------------

**Testing Environment -** 

<Details>

* WordPress: 6.1.1
* Theme: Storefront Version: 4.2.0
* WooCommerce - Version 7.1
* PHP: 8.0.0 
* Web Server: Nginx
* Browser: Chrome - Version 107.0.5304.87
* OS: macOS Monterey V 12.3.1
* Git Branch: fix/308

</Details>

**Steps to Test-** As mentioned in the PR description. 

**Test Results -** It is working as expected now. 

**Functional Demo /  Screencast -**

Screenshot 2022-12-02 at 5 54 13 PM




**Next Step-** Ready to Code Review(Woo)

**Review by ankitguptaindia — APPROVED** [review]

**Comment by vikrampm1** [comment]
@Konamiman this PR is awaiting your review.

**Review by Konamiman — APPROVED** [review]

**Comment by Konamiman** [comment]
Sorry, approved.

**Comment by ankitguptaindia** [comment]
**Regression Test Report-** ✅ 
------------

**Testing Environment -** 


<Details>

* WordPress: 6.1.1
* Theme: Storefront Version: 4.2.0
* WooCommerce - Version 7.2.2
* PHP: 8.0.0 
* Web Server: Nginx
* Browser: Chrome - Version 108.0.5359.124
* OS: macOS Monterey V 12.3.1
* Git Branch:  `testing`

</Details>




**Test Results -** Working expected with the `testing` branch. 
**Next Step-**   Ready to UAT.

**Comment by dkotter** [comment]
**Smoke Test Report-** ✅ 
-------

Tested with Archive File created via `php woorelease.phar build https://github.com/woocommerce/woocommerce-accommodation-bookings/tree/smoke-testing` (Composer version 2.5.1, npm version 6.14.14, node version 16.18.1, WP version 6.1.1, WooCommerce version 7.3.0, PHP version 8.1.9)

**Status-** Working as expected with Plugin Archive/Zip file. Able to install and activate plugin.

**Next Step-** Ready to Merge 🚀

**Pull request merged**
