### PR TITLE
Fix display of 2 checkbox options in Accomodation product

### PR DESCRIPTION
**Pull request by axi**
Fix display of checkbox options "user_can_cancel" & "requires_confirmation" in admin when db value is boolean

### All Submissions:

* [x] Does your code follow the [WooCommerce Sniffs](https://github.com/woocommerce/woocommerce-sniffs/) variant of WordPress coding standards?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?
* [ ] Will this change require new documentation or changes to existing documentation?

---

### Changes proposed in this Pull Request:

WC_Product_Booking following methods use boolean values, our Accomodation booking plugin must be able to understand boolean values from database (and not only "yes", "no")
```

	/**
	 * Get requires_confirmation.
	 *
	 * @param  string $context
	 * @return boolean
	 */
	public function get_requires_confirmation( $context = 'view' ) {
		return $this->get_prop( 'requires_confirmation', $context );
	}

	/**
	 * Set requires_confirmation.
	 *
	 * @param boolean $value
	 */
	public function set_requires_confirmation( $value ) {
		$this->set_prop( 'requires_confirmation', wc_bookings_string_to_bool( $value ) );
	}

```

### Steps to test the changes in this Pull Request:

1. Woocommerce > Products > Add new
2. Fill a title, select "Bookable product", check the "Requires confirmation?" checbox and save
3. _wc_booking_requires_confirmation	= **1** in database

--
   
1. Woocommerce > Products > Add new
2. Fill a title, select "Accomodation product", check the "Requires confirmation?" checbox and save
3. _wc_booking_requires_confirmation	= **yes** in database

At this point, I'm a bit lost. I guess the plugin should follow the "base" require_confirmation type but I'm not sure anymore if my fix is the good way to do so.

### Changelog entry

> Fix  - Display of 2 checkbox options in Accommodation product.

### CODE REVIEW

**Comment by axi** [comment]
I retrieved my use case :-)
Using WC_Bookings_REST_Products_Controller to create products through rest api, requires_confirmation param HAS to be boolean (see get_booking_product_properties()).
Products created this way have a _wc_booking_requires_confirmation = 1 in database and therefore, because template for displaying Accomodation product in admin was only supporting yesno values, my checkbox wasn't check

**Comment by vikrampm1** [comment]
@dkotter noting that this PR is awaiting your review.

**Review by dkotter — APPROVED** [review]

**Comment by ankitguptaindia** [comment]
Hi @axi,

Thank you for creating this PR. I attempted to test this issue by sending a REST API request, but it does not update the Accommodation Type product via REST API. 

I can test when manually changing the DB `'meta_value' to '1' from 'yes'`. If the 'meta_value' is a boolean value (i.e., 1), then the 'Requires confirmation?' box remains checked after applying this PR and becomes unchecked without this PR.


### With trunk: 

| meta_value  | checkbox status |
|--------|--------|
| Screenshot 2024-05-23 at 9 39 38 PM | Screenshot 2024-05-23 at 9 23 27 PM |
| Screenshot 2024-05-23 at 9 40 45 PM | Screenshot 2024-05-23 at 9 20 04 PM | 


### With this PR: 

| meta_value  | checkbox status |
|--------|--------|
| Screenshot 2024-05-23 at 9 41 42 PM | Screenshot 2024-05-23 at 9 21 47 PM | 
| Screenshot 2024-05-23 at 9 42 22 PM  | Screenshot 2024-05-23 at 9 22 41 PM | 




I am wondering about testing this PR via the REST API. Would you mind sharing a video about your use case if possible? Thanks!

**Comment by axi** [comment]
@ankitguptaindia 
In my usecase, I extend the WC_Bookings_REST_Products_Controller so I can't easily make a video about it. Is this problematic to approve that PR?

**Comment by ankitguptaindia** [comment]
Hello @axi,
It's not problematic, but it's part of our QA process to first reproduce the issue and then confirm if the PR fixes it. My concern with this PR is that the method to reproduce the issue is somewhat hacky. If we have a reliable way to reproduce the issue for QA, we can proceed to approve/merge the PR if it resolves the problem.

**Comment by axi** [comment]
@ankitguptaindia 
To be able to create accommodation booking via API, there's a hack. I have submit it to woocommerce-booking team 4 or 5 months ago (via their support) but they are not able to tell me if and when they will fix it... I have kind of abandonned the idea they will fix it and I keep reporting my fix on every release they make (at least they don't release very often :-) ) @ See more here: https://github.com/woocommerce/woocommerce-accommodation-bookings/issues/401

**Comment by ankitguptaindia** [comment]
Thanks, @axi, for providing the details. I appreciate your great work here. I have referenced this PR as it is blocked by issue  https://github.com/woocommerce/woocommerce-accommodation-bookings/issues/401#issuecomment-2136491673

**Comment by axi** [comment]
Hi,
#401 is now closed, we can finish this PR.
Here are the requests to test it
```HTTP
@productId = 42969
@siteUrl = 'http://localhost'
```

Allowed, will set postmeta.meta_key = "_wc_booking_requires_confirmation" to ""
```HTTP
PUT {{siteUrl}}/wp-json/wc-bookings/v1/products/{{productId}} HTTP/1.1
Authorization: Basic {{WC_CONSUMER_KEY}} {{WC_CONSUMER_SECRET}}
Content-Type: application/json; charset=utf-8

{
    "type": "accommodation-booking",
    "requires_confirmation": 0
}
```

Allowed, will set postmeta.meta_key = "_wc_booking_requires_confirmation" to "1"
```HTTP
PUT {{siteUrl}}/wp-json/wc-bookings/v1/products/{{productId}} HTTP/1.1
Authorization: Basic {{WC_CONSUMER_KEY}} {{WC_CONSUMER_SECRET}}
Content-Type: application/json; charset=utf-8

{
    "type": "accommodation-booking",
    "requires_confirmation": 1
}

```

NOT-Allowed => "requires_confirmation is not of type boolean."
```HTTP
PUT {{siteUrl}}/wp-json/wc-bookings/v1/products/{{productId}} HTTP/1.1
Authorization: Basic {{WC_CONSUMER_KEY}} {{WC_CONSUMER_SECRET}}
Content-Type: application/json; charset=utf-8

{
    "type": "accommodation-booking",
    "requires_confirmation": "yes"
}
```

NOT-Allowed => "requires_confirmation is not of type boolean."
```HTTP
PUT {{siteUrl}}/wp-json/wc-bookings/v1/products/{{productId}} HTTP/1.1
Authorization: Basic {{WC_CONSUMER_KEY}} {{WC_CONSUMER_SECRET}}
Content-Type: application/json; charset=utf-8

{
    "type": "accommodation-booking",
    "requires_confirmation": "no"
}
```

**Comment by ankitguptaindia** [comment]
**QA/Test Report-** ✅ 
------------

**Testing Environment -** 

<Details>

* WordPress: 6.6
* Theme: Storefront Version: 4.6.0
* WooCommerce - Version 9.1.2
* PHP: 8.3
* Web Server: Nginx
* Browser: Chrome - Version 126
* OS: macOS Sonoma 14.5
* Git Branch: axi:fix-checkboxes


</Details>




**Test Results -**  

I tested PR by creating Booking and Accommodation Booking products via REST API, `_wc_booking_requires_confirmation`  meta value updates according to boolean values in both plugins now. Previously only Booking Product updates `_wc_booking_requires_confirmation` values in boolean. After the fix in this PR, accommodation booking also follows the same approach. 




**Functional Demo /  Screencast -**



https://github.com/user-attachments/assets/59759342-01c6-497c-a096-1a7b07e8a4ec


**Next Step-** Ready to UAT. 

----

Thanks, @axi for your contribution to this extension.

**Review by ankitguptaindia — APPROVED** [review]

**Comment by ankitguptaindia** [comment]
**Regression+Smoke Test Report-** ✅ 
------------

**Testing Environment -** 


<Details>

* WordPress: 6.6.1
* Theme: Storefront Version: 4.6.0 / Twenty Twenty-Four Version: 1.2
* WooCommerce - Version 9.1.4 
* PHP: 8.3
* Web Server: Nginx
* Browser: Chrome - Version 127
* OS: macOS Sonoma 14.5


</Details>

Tested with Archive File created via woorelease command. 

- Composer version - v2.3.5
- npm version - v10.1.0
- node version - v20.7.0



**Status-**  Working as expected. Ready to merge 🚀

**Pull request merged**
