### PR TITLE
[PHP 8] Explicitly cast values to float before applying the "abs" function where needed

### PR DESCRIPTION
**Pull request by Konamiman**
### All Submissions:

* [ ] Does your code follow the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changes proposed in this Pull Request:

There's a couple of places in the code where the built-in function `abs` is executed passing a non-numeric value (not a number and not a string that can be parsed as a number), for example `abs('')`. In PHP 7 this yields a value of 0, but in PHP 8 this throws an error.

This commit casts the value to `float` before applying the `abs` function, this fixed the issue since `(float)''` evaluates to zero.

### How to test the changes in this Pull Request:

With PHP 8 active, and without the patch, activate the plugin (the Bookings plugin is required too) and try to create an accommodation product: it will throw an error. Apply the patch and retry, it will work now.

### Other information:

* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changelog entry

> Dev - Fix: Add casts to float before applying the 'abs' function to potentially empty strings for compatibility with PHP8.

### CODE REVIEW

**Comment by peterfabian** [comment]
@ObliviousHarmony can you please review or find another reviewer?

**Review by ObliviousHarmony — COMMENTED** [review]
Hey @Konamiman,

While the fix itself works appropriately, I have some questions about the infrastructure and architecture changes in this PR. I'm not really a fan of the namespace and think perhaps we should discuss some of these things before we commit to them in the plugins we maintain.

Perhaps @roykho can give insight here?


I think before adding PSR-4 to this plugin that perhaps we should discuss both the namespacing (As the length of this leads something to be desired!), as well as whether or not

**Comment by peterfabian** [comment]
@roykho can you please share your view on @Konamiman 's work so that we can move this discussion along? Thanks!

**Comment by roykho** [comment]
So I don't have issues with PSR-4 namespacing in general however this seems to be a discussion we should have in the grand scheme of things so that we can adopt the same architecture across all extensions.

For this particular fix, it seems an overkill. IMO the use of `abs` is incorrect in this context from the beginning.  Perhaps we could just use `(float)` to cast the values. If there is a negative value coming in, something else is wrong upstream and should be fixed there.

**Comment by peterfabian** [comment]
I tend to agree with @roykho and @ObliviousHarmony . 
I think converting the code from `abs( X )` to `abs( (float) X )` is probably doing the same thing as it was before and should work in PHP 8, too. 
Based on [the past review](https://github.com/woocommerce/woocommerce-accommodation-bookings/pull/260#discussion_r474973879), the `abs` seems to be needed, I think?

@Konamiman can you please try the more light-weight approach?

**Comment by Konamiman** [comment]
@peterfabian @ObliviousHarmony @roykho For WooCommerce core we have decided that any new code should follow be PSR4-named and located, since that will help on keeping the code readable, testable and maintainable. It was my understanding that we want to have the same benefits in the WooCommerve extensions, and that it wouldn't hurt to add the necessary scaffolding for that even if it was overkill for this particular fix.

That said, yes, I agree that in this case adding a couple of casts to `float` fixes the issue in a much simpler way; and simplicity of code is as important as its readability. So I have done just that: all the PSR4 infrastructure is now removed.

I still think that as soon as we find the need to do any moderately complex change to the code we should use it as an opportunity to PSR4-ify the codebase (for new code, in the same way we've done in core), though.

**Review by ObliviousHarmony — APPROVED** [review]
LGTM!

**Pull request merged**
