### PR TITLE
Fix incorrect calculation and display of accommodation availability in the date picker

### PR DESCRIPTION
**Pull request by robertstaddon**
With multiday bookings, the WC_Product_Booking class checks the availability of each block in the selected range of dates. This is calculated incorrectly because the is_booked_on_day method of the WC_Booking class does not take into account blocks that both start and end before the booking date starts or after it ends. This pull request modifies the WC_Accommodation_Booking class to hook into the "woocommerce_booking_is_booked_on_day" filter and fix this.

The error message displayed to the user when the get_blocks_availability method of the WC_Product_Booking class encounters a block with no availability incorrectly reports the number of available spaces from whatever block had the maximum number. This pull request overrides the get_blocks_availability function in the WC_Product_Accommodation_Booking class to return the correct error.

### CODE REVIEW

**Comment by dwainm** [comment]
@robertstaddon thank you for the PR, we're making some changes in bookings core now which may affect this PR, so I'd like to land that before inspecting this one.

**Comment by dwainm** [comment]
@jessepearson would you mind confirming this on the latest version of bookings?

**Comment by jessepearson** [comment]
@robertstaddon This PR was done before Accomm was made compatible with WooCommerce 3+ and Bookings 1.10+, so it causes a fatal error when trying to test it out. Would you be able to first check to see if there's still an issue with Bookings 1.10.3 and Accommodations master, and if so, could you then update the PR so that the code is added into the latest version of Accommodations so it does not create a fatal error. 

Also, can you confirm how this affects the availability calendar or the bookings themselves? I'd like to know how to test what you are saying is happening.

**Comment by dwainm** [comment]
@robertstaddon feel free to open a new PR  as this one is out of sync with the master branch.

**Pull request closed without merging**
