### PR TITLE
Fix/issue 201

### LINKED ISSUE #201: Fully booked days show as partially booked - Day after booking shows partially booked.
#### Affected ticket(s)

1502723-zen
8433091-hc
2108399-zen

#### What I expected

Let's say I have a Yurt that I rent out using Accommodation Bookings - there is only 1 yurt so only one available room.

If I book a date, say just 1 night, then, come back to the Calendar, the check-in date shows "partially booked" - but it's fully booked:

http://cld.wthms.co/wR5sre
Image link: http://cld.wthms.co/wR5sre

Additionally, the day *after* shows partially booked(same screenshot above). 

I personally think that it doesn't make sense for Accommodation Bookings to consider something 'partially booked' at all. When you're selecting a room you only care about that room being available from check-in time to check-out time. It doesn't matter if someone had the room before you or after you.

It seems like Accommodation Bookings needs to have some extra logic for these scenarios as it appears to just be using Bookings logic which adds the `partial_booked` class to days which are booked and the day after(because technically the booking bleeds into the next day).

#### Steps to reproduce the issue

* Create a new Accommodation Booking product
* Set its "number of rooms available" to 1
* Set a price
* Book a date, say, just 1 night. Complete checkout.
* Go back to the product page and observe that the booked date(which is unavailable) has the `partial_booked` class applied as well as the next day.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

### PR DESCRIPTION
**Pull request by superdav42**
Fixes #201  .

#### Changes proposed in this Pull Request:
- Adds the fields `fully_booked_for_start_day` and `fully_booked_for_end_day` so the date picker can determine which days should be available for checkin and checkout.

-------------------
- [ ] Make sure your changes respect [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [ ] Did you make changes, or create a **new .js file**? If **Gruntfile.js** exists in the repo, make sure to run `grunt`.

### CODE REVIEW

**Comment by roykho** [comment]
I am not sure if its working correctly on my end. I have 11/25 to 11/26 and 11/28 to 11/29 for check-in and check-out dates. When I click into the date field, I see the following  If I enter 11/30, I see this The 25th shouldn't show (it should be white). However if I enter 11/25 (in the past) I see this  25th should be white 26th should not be red/crossed out because its still available to book from 26th to 27th. 29th shouldn't be red/crossed out either as it is available for booking.

**Comment by superdav42** [comment]
> I am not sure if its working correctly on my end. I have 11/25 to 11/26 and 11/28 to 11/29 for check-in and check-out dates. When I click into the date field, I see the following  
If I enter 11/30, I see this The 25th shouldn't show (it should be white). 

It's showing as red because there is a a booking on that day. All dates marked before the checkin date are being marked as white expect the ones which have a booking and they stay red.

> However if I enter 11/25 (in the past) I see this  25th should be white 26th should not be red/crossed out because its still available to book from 26th to 27th. 29th shouldn't be red/crossed out either as it is available for booking.

I'm not sure what it should do in this case. The 25th should not be available for checkin. Did you manually enter it? Not sure what it should do in this case.

**Comment by roykho** [comment]
> It's showing as red because there is a a booking on that day. All dates marked before the checkin date are being marked as white expect the ones which have a booking and they stay red.

Right however what I am saying is the display before clicking into the date field shows something different from after clicking into it.

> The 25th should not be available for checkin. Did you manually enter it? Not sure what it should do in this case.

25th should not be bookable and its correct. I am referring to 26th which should be available for check-in.

**Comment by bor0** [comment]
Closing stale PR.

**Pull request closed without merging**
