### PR TITLE
Fix/290 `float` used to convert blank cost to `0`

### LINKED ISSUE #290: Fatal error with PHP 8.0.xx when Base Cost/Block Cost is empty while adding a resource in Accommodation Product
#### Affected ticket(s)

4806348-zen

#### What I expected

The product should be published or updated.

#### What happened instead

but it throws a fatal error: https://d.pr/i/ZADeQd

#### Steps to reproduce the issue

**Make sure the website is on PHP 8.0.xx before testing**

1) Try publishing a new Accommodation product with only WooCommerce, WC Bookings, and Accommodation Bookings plugins as active.
2) Add new product > Select Type as **Accommodation Product**
3) Tick mark the "Has Resources" option and add a resource.
4) Keep one of the values for Base Cost or Block Cost as empty
5) Publish the product -> Results into WP critical error.

Error log:

`2022-02-25T06:48:08+00:00 CRITICAL Uncaught TypeError: Unsupported operand types: string + string in /var/web/staging/public_html/wp-content/plugins/woocommerce-accommodation-bookings/includes/admin/class-wc-accommodation-booking-admin-panels.php:261`

Seems like a known issue with PHP 8.0 when we try to add blank items in array:

`if ( ( $resource_base_cost[ $i ] + $resource_block_cost[ $i ] ) > 0 ) {`

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

### PR DESCRIPTION
**Pull request by faisal-alvi**
### All Submissions:

* [ ] Does your code follow the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changes proposed in this Pull Request:

This PR uses float type to convert blank string additions (string + string) to be (0 + 0).

Closes #290.

### How to test the changes in this Pull Request:

1. Create an accommodation product.
2. Tick the “Has Resources” checkbox.
3. Add some resources.
4. Make sure to keep the base cost and/or block cost empty.
5. Save the product.
6. Product should be saved without any errors.

### Other information:

* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changelog entry

> Fix - Fatal error with PHP 8.0 when Base Cost/Block Cost is empty.

### CODE REVIEW

**Review by dkotter — APPROVED** [review]

**Review by jorgeatorres — APPROVED** [review]
👍

**Comment by ankitguptaindia** [comment]
**QA/Test Report-**
------------

**Testing Environment -** 

<Details>

**Latest-**

* WordPress: 6.0
* Theme: Storefront Version: 4.1.0
* WooCommerce - Version 6.5.1
* PHP: 8.0.0 
* Web Server: nginx
* Browser: Chrome - Version 99.0.4844.84
* OS: macOS Monterey V 12.3
* Console Log: All fine
* WP Debug Log: All fine.

</Details>

**Steps to Test-** As mentioned in the PR description and explained in the attached demo video.

**Test Results -** Tested on 'Latest' test environment. It is working as expected.  

**Functional Demo /  Screencast -**

https://user-images.githubusercontent.com/6384299/170723368-df15410d-98e7-4760-b711-df98c28f2723.mp4



**Next Step-** Ready to ~~Code Review(Woo)~~ Regression

**Review by ankitguptaindia — APPROVED** [review]

**Comment by ankitguptaindia** [comment]
@dkotter As this is already reviewed by Woo team so ready for merging in `regression`

**Comment by dkotter** [comment]
This is in the `testing` branch now

**Comment by ankitguptaindia** [comment]
**Regression Test Report-**
------------

**Testing Environment -** 

<Details>

**Latest-**

* WordPress: 6.0
* Theme: Storefront Version: 4.1.0
* WooCommerce - Version 6.5.1
* PHP: 8.0.0 
* Web Server: nginx
* Browser: Chrome - Version 101.0.4951.64
* OS: macOS Monterey V 12.3.1
* Console Log: All fine
* WP Debug Log: All fine.


**Oldest -**

* WordPress: 5.7.5
* Theme: Storefront - 3.6.0
* WooCommerce -  5.7.1
* PHP: 7.0
* Web Server: Apache
* Browser: FireFox Version - 94.0.1
* OS: macOS Monterey V 12.0.1
* Console Log: All fine
* WP Debug Log: All fine.

</Details>



**Test Results -** Working expected with the `testing` branch. 
**Next Step-**   Ready to UAT.

**Review by ankitguptaindia — APPROVED** [review]

**Comment by ankitguptaindia** [comment]
**Smoke Test Report-**
---- 

Tested with Archive File created via "php woorelease.phar build repo_URL" (Composer version 2.1.5, npm version 6.14.14, node version 12.8.0)

**Status-** Working expected with Plugin Archive/Zip file same as fix specific branch. 


 **Next Step-** Ready to Merge 🚀

**Pull request merged**
