### PR TITLE
Add availability option that allows checkout but stops check in.

### LINKED ISSUE #147: Can't block certain dates for checkin only
#### Affected ticket(s)

726671-zen

#### What I expected

To disable checkin on October 31st (but still let customers check out on that day)

#### What happened instead

I've added the following availability rules:

Screenshot
Screenshot: http://cld.wthms.co/DZqL1O

All dates with a 'No' can't be selected in the calendar, even as a checkout date:

Screenshot
Screenshot: http://cld.wthms.co/V89C7w

Global availability rules taking checkin and checkout hours also don't help.

#### Steps to reproduce the issue

1. Create an accommodation product and add a few rules excluding certain dates (i.e. as above)
2. Open the product on the frontend and observe this day can't be used for checkout
3. Delete all rules on the product and replace them with a Global Availability rule that has a date range with time:

Screenshot
Screenshot: http://cld.wthms.co/cQqlse

4. Observe this time you're both able to checkin and checkout on that day, despite it should be blocked for checkin.

Screenshot
Screenshot: http://cld.wthms.co/y3MloS

Reproduced on Pressable, Bookings 1.10.8 & Accommodations 1.1.0

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

### PR DESCRIPTION
**Pull request by budzanowski**
Fixes #147 .

This requires https://github.com/woocommerce/woocommerce-bookings/pull/1781 in order to work.

### CODE REVIEW

**Comment by roykho** [comment]
@budzanowski whatever happened to this? It seems #1781 is also approved?

**Comment by budzanowski** [comment]
@roykho I totally forgot about this. I will review the changes on both Issues and try to get it in.

**Comment by budzanowski** [comment]
@roykho you still need the separation of a day you can't book at all, no check-in, no check-out, no nothing and a day that can be a last day of the booking but can't be the start of a booking. It would be nice to do it automatically and assume that this is the case if we are dealing with accommodation-bookings but this would be a big BC breaking change. Merchants need the option in my opinion.

**Comment by roykho** [comment]
@budzanowski If you want to keep the setting, docs may need to be updated because it is not clear what that means for users. Also if you add that setting to product level, you should add it to global availability too for consistency.

**Comment by budzanowski** [comment]
I would like to not add this to global availability. This would be confusing bc this affects only accommodation types of products. That is why I would like the scope to be limited. I am afraid that this could have consequences to how other types of products would behave while being affected by having this option acting on them. I know that this is not ideal but in this case, I would gladly go with the minimal required change to mitigate the problem merchants have. Is the global availability symmetry really required here?

Docs ofc need a change.

**Comment by roykho** [comment]
I can understand that however what if the merchant just sells rooms and they don't want to set each and every availability at product level so they want to use global availability to do it once?

**Comment by budzanowski** [comment]
Yes that is how I see it. We are giving an option that can fix their problem and this option is not the most convenient to use :/ This is not a lack of empathy towards merchants but rather me being afraid that this option inside global availability will mess things up. Should this be a roundtable discussion? I don't try to force my solution or something, just trying to explain how I see this.

**Comment by c-shultz** [comment]
We would need a bigger time investment and design involvement to solve this properly (per slack convo: https://a8c.slack.com/archives/CAKN301C3/p1563547720335600)

**Pull request closed without merging**
