### PR TITLE
Fix price sorting by fixing product_meta_lookup min_price & max_price

### LINKED ISSUE #434: Price for sorting is incorrect
#### What I expected
I expect the orderby=price-asc order by to be working correctly

#### What happened instead
Values saved in lookup_table are wrong, resulting order is wrong

#### Steps to reproduce the issue
Note 1: It looks like this happen only after an "update", not on creation.
Note 2: this is the query I use in the following steps to get the values
```mysql
SELECT
    pm.post_id,
    pml.min_price,
    pm2.meta_value as '_price',
    pm3.meta_value as '_wc_booking_min_duration'
FROM wp_postmeta pm
    LEFT JOIN wp_wc_product_meta_lookup pml ON pml.product_id = pm.post_id
    LEFT JOIN wp_postmeta pm2 ON pm.post_id = pm2.post_id AND pm2.meta_key = '_price'
    LEFT JOIN wp_postmeta pm3 ON pm.post_id = pm3.post_id AND pm3.meta_key = '_wc_booking_min_duration'
WHERE pm.post_id IN (MY_CREATED_PRODUCT_IDS)
GROUP BY pm.post_id
ORDER BY pm.post_id
```

Create an accommodation product with the following:
- Name: product1
- Minimum number of nights allowed in a booking: 2010
- Standard room rate: 150
- hit "publish" button

| min_price | _price | _wc_booking_min_duration |
|-----------|--------|--------------------------|
| 0         | 150    | 2010                     |

- trigger a save with "update" button

| min_price | _price | _wc_booking_min_duration |
|-----------|--------|--------------------------|
| 301500.0000         | 150    | 2010                     |

Create  another accommodation product with the following:
- Name: product2
- Minimum number of nights allowed in a booking: 10
- Standard room rate: 200
- hit "publish" button

| min_price | _price | _wc_booking_min_duration |
|-----------|--------|--------------------------|
| 0         | 200    | 10                     |

- trigger a save with "update" button

| min_price | _price | _wc_booking_min_duration |
|-----------|--------|--------------------------|
| 2000.0000         | 200    | 10                     |

When using sorting by price asc, we want the cheapest first (Product1) but we have Product2 first.

This is because lookup_table gets a calculated value that take the min number of nights into account (see `WC_Bookings_Cost_Calculation::calculated_base_cost()`)... 

WC_Accommodation_Booking_Admin_Panels::save_product_data() tries to solve that l424:
```php
public function save_product_data( $post_id ) {
    ....
    // Set price so filters work - using get_base_cost()
    $product = wc_get_product( $post_id );
    update_post_meta( $post_id, '_price', $product->get_base_cost() );
}
```

but at that time, price is already set in lookup table.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

### PR DESCRIPTION
**Pull request by axi**
### All Submissions:

* [x] Does your code follow the [WooCommerce Sniffs](https://github.com/woocommerce/woocommerce-sniffs/) variant of WordPress coding standards?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?
* [ ] Will this change require new documentation or changes to existing documentation?

---

### Changes proposed in this Pull Request:
Update the min_price & max_price values in wc_product_meta_lookup that has been wrongly set to unique cost times duration by the booking data store.

Closes #434 .

### Steps to test the changes in this Pull Request:
Check the "Steps to reproduce the issue" in #434 issue

### CODE REVIEW

**Review by dkotter — APPROVED** [review]

**Comment by axi** [comment]
Hi @ankitguptaindia, what means the draft status ? Does it need something on my side ?

**Comment by ankitguptaindia** [comment]
@axi This is our part of the process. we keep PR status in draft until we complete our QA/UAT processes so nothing from your side until we find anything in QA/UAT.

**Comment by axi** [comment]
Any news on that PR ?

**Comment by vikrampm1** [comment]
@ankitguptaindia @Sourabh208 This PR is awaiting QA, please prioritize it in your queue.

**Comment by ankitguptaindia** [comment]
Hello @axi,

Thank you for your contribution to this extension, and we genuinely appreciate your patience with this PR. The review took longer than expected as the team was occupied with other high-priority tasks.

In our testing, everything has passed, and the PR looks ready for the next steps. No further action is required from your side at this point. If it successfully passes our UAT as well, we will proceed to merge it for the upcoming release.

Thank you once again for your efforts!

**Comment by ankitguptaindia** [comment]
-----

**QA/Test Report-** ✅ 
------------

**Testing Environment -** 

<Details>

* WordPress: 6.7
* Theme active on store: Storefront
* WooCommerce - Version 9.4.2
* PHP: 8.3
* Web Server: Nginx
* Browser: Chrome - Version 131
* OS: macOS Sonoma 14.6.1 

</Details>

**Test Results -** Issue has been fixed and other tests pass this PR. 


**Functional Demo /  Screencast -** 

**Before:**
image


**After:** 

image


**Next Step-** Ready to UAT

**Review by ankitguptaindia — APPROVED** [review]

**Pull request merged**
