### PR TITLE
Update dependencies

### LINKED ISSUE #284: Update npm packages
There are several old packages, so we should run update to get them updated and test if everything works as expected.

### PR DESCRIPTION
**Pull request by dkotter**
### All Submissions:

* [x] Does your code follow the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changes proposed in this Pull Request:

Update our npm dependencies. This PR replaces the following PRs that were opened by dependabot:

- #277 
- #279 
- #280 
- #282 
- #286 
- #287 

### How to test the changes in this Pull Request:

1. Ensure you are running node v10 and npm v6 or below, as the way we are building assets is no longer supported as of [npm 7](https://github.com/npm/cli/blob/latest/changelogs/CHANGELOG-7.md#all-lifecycle-scripts). No changes to this were made in this PR, this is existing functionality, but would be nice to modernize this
2. On a clean install, run `npm install`
3. Then run `npm run build:dev`
4. Ensure a single CSS file is created properly, a single minified JS file is created properly and a single POT file is created
5. Test that any functionality that relies on the CSS or JS files still works as intended

### Other information:

* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changelog entry

> Update all npm dependencies.

### CODE REVIEW

**Review by Sidsector9 — APPROVED** [review]
Tested the following commands:

- [x] prebuild
- [x] build
- [x] build:dev
- [x] archive
- [x] postarchive
- [x] preuglify
- [x] uglify
- [x] presass
- [x] sass
- [x] watchsass
- [x] postsass
- [x] makepot

LGTM 👍

**Comment by ankitguptaindia** [comment]
**Test Report-**
--------


Tested all major functionality of plugin after creating build via `npm run build` with **Composer version 2.1.5, npm version 6.14.14, node version 12.8.0**
 Also tested build created via **woo release command**  i.e.   `php woorelease.phar build ...` 
 
**_The build is creating fine without any error/notice/warnings._**

**Comment by ankitguptaindia** [comment]
Hi @dkotter As this PR update dependencies so can we skip Woo Code review and directly move to the next UAT? 
If yes, please merge in `testing`  branch.  thankyou!

**Review by ankitguptaindia — APPROVED** [review]

**Comment by dkotter** [comment]
This is in the `testing` branch now

**Comment by ankitguptaindia** [comment]
**Regression Test Report-**
------------

**Testing Environment -** 
<Details>

**Latest-**

* WordPress: 6.0
* Theme: Storefront Version: 4.1.0
* WooCommerce - Version 6.6.0
* PHP: 8.0.0 
* Web Server: nginx
* Browser: Chrome - Version 101.0.4951.64
* OS: macOS Monterey V 12.3.1
* Console Log: All fine
* WP Debug Log: All fine.


**Oldest -** 

* WordPress: 5.7.5
* Theme: Storefront - 3.6.0
* WooCommerce -  5.7.1
* PHP: 7.0
* Web Server: Apache
* Browser: FireFox Version - 94.0.1
* OS: macOS Monterey V 12.0.1
* Console Log: All fine
* WP Debug Log: All fine.

</Details>



**Test Results -** Working expected with the `testing` branch. 
**Next Step-**   Ready to UAT.

**Review by ankitguptaindia — APPROVED** [review]

**Comment by ankitguptaindia** [comment]
Tested with Archive File created via "php woorelease.phar build repo_URL" (Composer version 2.1.5, npm version 6.14.14, node version 12.8.0)

**Status-** Tested main functionality of the extension, working expected. 


 **Next Step-** Ready to Merge 🚀

**Review by ankitguptaindia — APPROVED** [review]

**Pull request merged**
