### PR TITLE
Set the minimum value for max nights to 1

### LINKED ISSUE #148: Maximum number of nights allowed option set to 0 breaks page
#### Affected ticket(s)

zd-woothemes-743674

#### What I expected

Under the General tab is the Minimum and Maximum number of nights allowed in a booking.

When you set `Maximum number of nights allowed in a booking` to `0` and update, it should not save and should throw an error that a minimum value is required.

#### What happened instead

The customer was able to save the `0` value.

Replicating myself, I am not able to save the `0` value, but entering `0` and clicking on update, the page does nothing. No error messages, nothing. Any attempts at this point to update the page are ignored, you have to refresh.

The error in the browser's console log is:

see screen shot

#### Steps to reproduce the issue

1. Using Accommodations, create a product. It does not matter the specifics, the minimum is fine.
2. Go to the General tab after creating and set `Maximum number of nights allowed in a booking` to `0`
3. Click on the Update button. The page should do nothing, it won't save or thrown an error. For the customer it actually does allow you to save the `0` value, but with that value at `0`, you cannot save the page, so essentially the same behavior.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

### PR DESCRIPTION
**Pull request by SiR-DanieL**
Fixes #148

#### Changes proposed in this Pull Request:
- Set the `min` value of the field to `1`.

-------------------
- [x] Make sure your changes respect [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [x] Did you make changes, or create a **new .js file**? If **Gruntfile.js** exists in the repo, make sure to run `grunt`.

### CODE REVIEW

**Comment by Luminus** [comment]
@justinshreve could you please review this when you've got a minute so we can merge it and possibly send the user a pre-release version if the next version isn't being pushed out soon.

Thanks loads.

**Comment by justinshreve** [comment]
The change looks okay to me, but I haven't been involved with bookings or accommodation bookings in awhile (been on a different team for awhile now) so it's probably best to have someone like @bor0 give the final say.

**Comment by Luminus** [comment]
Thanks @justinshreve. We'll wait for @bor0 to give it the once-over.

**Comment by bor0** [comment]
Thanks for your contribution!

**Pull request merged**
